### ISSUE TITLE
Flake8 optparse conflict when invoking as a module

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#59]
As noticed in the [recent CI failure](https://dev.azure.com/python-discord/Python%20Discord/_build/results?buildId=5198&view=results), flake8 is raising a configuration option conflict when attempting to add the newly inserted configuration option:

```bash
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/main/application.py", line 380, in _run
    self.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/main/application.py", line 364, in initialize
    self.register_plugin_options()
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/main/application.py", line 205, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/plugins/manager.py", line 489, in register_options
    list(self.manager.map(register_and_enable))
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/plugins/manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/plugins/manager.py", line 485, in register_and_enable
    call_register_options(plugin)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/plugins/manager.py", line 397, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/plugins/manager.py", line 216, in register_options
    add_options(optmanager)
  File "/home/vsts/work/1/s/flake8_annotations/checker.py", line 86, in add_options
    "Suppress TYP200-level errors for functions that contain no return statement or "
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/flake8/options/manager.py", line 231, in add_option
    self.parser.add_option(option.to_optparse())
```

I've traced this to a discrepancy in behavior between invoking flake8 via the installed entry point (e.g. `flake8`) and invoking as a module (e.g. `python3 -m flake8`) as we're doing in the CI configuration.

While adjusting the CI configuration should resolve the issue, I've [reported upstream](https://gitlab.com/pycqa/flake8/issues/610) to see if this is indeed a bug or something working as intended that I've missed.

**Comment by sco1** [comment]
Per the upstream issue, this seems to be an issue with `entrypoints`, as the issue disappears when `flake8` is installed from the master branch rather than from PyPI. `flake8` is switching from `entrypoints` to `importlib_metadata`.

Short term, this should be a simple resolution of adjusting the Azure pipeline config to utilize `flake8` vs. `python3 -m flake8`. I'd rather go with this approach than pinning `flake8` away from PyPI.

**Comment by sco1** [comment]
Resolved by https://github.com/python-discord/flake8-annotations/commit/10dcbc573725c41148873b7dfe39b5b940d89a64
